version: '3.3'

services:
  redis:
    image: redis:5
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - redis-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: always
    networks:
      - redis-network

networks:
  redis-network:


